"""Choose Your Own Adventure Project."""

__author__ = "730389141"


from random import randint

player: str = ""
points: int
running = True
SECRET: int = 6
SMILEY: str = '\U0001f604'
SAD: str = '\U0001f615'


def greet() -> None:
    """Welcome function."""
    global player
    player = input("Enter your name: ")
    print(f"Hi, {player}! I hope you ready to play the guessing game! ")
    print("In this number guessing game, you need to guess the random number generated by the computer, or you may choose to guess a pre-stored number. You have 5 attempts per round and each round is independent.")


def main() -> None:
    """The game's entrypoint."""
    global running
    global points
    points = 0
    greet()
    while running:
        level_input: str = input("Type 'Easy' or 'Hard' to enter the level of difficulty of your choice for the random number generator game. Type 'Standard' if you choose to play with a pre-stored number without involving points. If you don't want to play the game, type 'Quit': ")
        if level_input == "Easy":
            print(f"Welcome to Easy mode, {player}! You need to guess a number between 1 and 5")
            easy(0)
        else:
            if level_input == "Hard":
                print(f"Welcome to Hard mode, {player}! You need to guess a number between 1 and 10")
                hard(0)
            else:
                if level_input == "Standard":
                    print(f"Welcome to the Standard mode, {player}! You need to guess a number between 1 and 20")
                    standard()
                else:
                    if level_input == "Quit":
                        print("You decided to not play anymore.")
                        print("Game over.")
                        running = False 
                    else:
                        print("Incorrect input")
                        main()
    print("Thank you for playing!")
               

def easy(points: int) -> int:
    """Easy mode."""
    random_number = randint(1, 5)
    count: int = 0
    while count < 5:
        guess: int = int(input("What is your guess? "))
        if guess < random_number:
            count = count + 1
            points = points + 1
            print("Your guess is too low")
        if guess > random_number:
            count = count + 1
            points = points + 1
            print("Your guess is too high")
        if guess == random_number:
            points = points + 1
            print("You got it right!" + SMILEY)
            print(f"{player}, you guessed the number after {points} tries. Your score is {points}")
            count = 5
    print(f"The random_number was {random_number}")
    return points


def hard(points: int) -> int:
    """Hard mode."""
    random_number = randint(1, 10)
    count: int = 0
    while count < 5:
        guess: int = int(input("What is your guess? "))
        if guess < random_number:
            points = points + 1
            count = count + 1
            print("Your guess is too low")
        if guess > random_number:
            points = points + 1
            count = count + 1
            print("Your guess is too high")
        if guess == random_number:
            points = points + 1
            print("You got it right!" + SMILEY)
            print(f"{player}, you guessed the number after {points} tries. Your score is {points}")
            count = 5
    print(f"The random_number was {random_number}")
    return points


def standard() -> None:
    """Standard mode."""
    points: int = 0
    count: int = 0 
    while count < 5:
        guess: int = int(input("What is your guess? "))
        if guess == SECRET: 
            points = points + 1
            print("You guessed correctly!!!" + SMILEY)
            print(f"Your score is { points }, depending on the number of tries you took!")
            print("Have a wonderful day!!!")
            count = 5
        else: 
            print("Sorry, you guessed incorrectly" + SAD)
            if guess > SECRET: 
                print("You guessed too high!")
                points = points + 1
                count = count + 1
            else: 
                print("You guessed too low!")
                points = points + 1
                count = count + 1
    print(f"The stored number is {SECRET}")
    return None


if __name__ == "__main__":
    main()